Vagrant.configure(2) do |config|
  config.vm.box = "debian/buster64"
  config.vm.provider "virtualbox" do |v|
          v.memory = 384
          v.cpus = 1
  end
  config.vm.define "wiki" do |dokuwiki|
    dokuwiki.vm.network "private_network", ip: "192.168.56.10"
    dokuwiki.vm.hostname = "wiki"
    dokuwiki.vm.provision "shell", inline: <<-SHELL
      sudo su
      cd /etc
      echo "*/5 * * * * wiki rsync --partial -r -e 'ssh -i /home/wiki/.ssh/id_rsa' /var/www/html/ wiki@192.168.56.11:/var/www/html/data" >> crontab
    SHELL
  end
  config.vm.define "backup" do |backup|
    backup.vm.network "private_network", ip: "192.168.56.11"
    backup.vm.hostname = "backup"
  end
  config.vm.provision "shell", inline: <<-SHELL
      sudo useradd -m -s /bin/bash -G www-data wiki
      mkdir /home/wiki/.ssh
      cp /vagrant/id_rsa /home/wiki/.ssh/
      cat /vagrant/id_rsa.pub >> /home/wiki/.ssh/authorized_keys
      chmod 700 /home/wiki/.ssh
      chmod 600 /home/wiki/.ssh/*
      chown -R wiki:wiki /home/wiki/.ssh
      echo "### Installation de php-geshi ###"
      sudo apt install php-geshi -y
      cd /var/www/html/
      echo "### Téléchargement de la dernière version de DokuWiki dans le dossier /var/www/html ###"
      sudo wget https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
      echo "### Extraction de l'élément téléchargé ###"
      sudo tar -xvf dokuwiki-stable.tgz
      echo "### Suppression de l'archive telecharge precedement ###"
      sudo rm -Rf dokuwiki-stable.tgz
      echo "### Suppression de index.html ###"
      sudo rm index.html
      cd dokuwiki-2018-04-22b/
      sudo mv * ../
      sudo chown -R www-data /var/www/html/
    SHELL
end
